name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Resolves Node 20 deprecation warning for GitHub Actions setup
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  laravel-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Running on Node.js 24 based on deprecation warnings

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Install NPM dependencies
      run: npm ci

    - name: Build Frontend
      run: npm run build

    - name: Database setup
      run: |
        touch database/database.sqlite
        php artisan migrate --graceful
        php artisan db:seed

    - name: Execute tests
      run: php artisan test
